// Local filesystem driver. The default: no credentials, no network, and the
// whole upload tree is one directory you can back up or rsync.
//
// Object keys become relative paths under the root. Keys are generated by
// ../index and validated before they get here, but the resolved path is
// checked against the root anyway, so a bug in key construction still cannot
// read or write outside the upload tree.
const fs = require('fs');
const fsp = require('fs/promises');
const path = require('path');
const { Readable } = require('stream');

let root = null;

function init(cfg) {
  root = cfg.root;
}

function resolveKey(k) {
  const abs = path.resolve(root, k);
  if (abs !== root && !abs.startsWith(root + path.sep)) {
    throw new Error('object key resolves outside the storage root');
  }
  return abs;
}

async function put(k, buffer) {
  const abs = resolveKey(k);
  await fsp.mkdir(path.dirname(abs), { recursive: true });
  await fsp.writeFile(abs, buffer);
  return { size: buffer.length, etag: null };
}

async function get(k) {
  return fsp.readFile(resolveKey(k));
}

function createReadStream(k) {
  return fs.createReadStream(resolveKey(k));
}

async function delete_(k) {
  try {
    await fsp.unlink(resolveKey(k));
  } catch (e) {
    // ENOENT is the expected steady state: the metadata row and the object are
    // not removed in one step, so a repeat call has to succeed.
    if (e.code !== 'ENOENT') throw e;
  }
}

async function exists(k) {
  try {
    await fsp.access(resolveKey(k));
    return true;
  } catch {
    return false;
  }
}

async function list(prefix) {
  const base = resolveKey(prefix || '');
  const out = [];
  async function walk(dir) {
    let entries;
    try {
      entries = await fsp.readdir(dir, { withFileTypes: true });
    } catch (e) {
      if (e.code === 'ENOENT') return;
      throw e;
    }
    for (const e of entries) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) await walk(full);
      else {
        const st = await fsp.stat(full);
        out.push({ key: path.relative(root, full).split(path.sep).join('/'), size: st.size });
      }
    }
  }
  await walk(base);
  return out;
}

module.exports = { init, put, get, createReadStream, delete: delete_, exists, list, name: 'local' };
